export interface StyleToken {
  variable: string
  label: string
  description: string
  labelKey: string
  descriptionKey: string
  type: "color" | "size" | "number" | "opacity" | "shadow"
  defaultValue: string
  cssFallback: string
  category: "core" | "advanced" | "submenu"
  min?: number
  max?: number
  step?: number
}

export const STYLE_TOKENS: StyleToken[] = [
  {
    variable: "--nav-bg",
    label: "导航栏背景色",
    description: "导航栏的背景颜色",
    labelKey: "lets-nav-helper.styleToken.navBg.label",
    descriptionKey: "lets-nav-helper.styleToken.navBg.desc",
    type: "color",
    defaultValue: "",
    cssFallback: "transparent",
    category: "core",
  },
  {
    variable: "--nav-btn-color",
    label: "按钮图标颜色",
    description: "导航栏按钮的图标与文字颜色",
    labelKey: "lets-nav-helper.styleToken.navBtnColor.label",
    descriptionKey: "lets-nav-helper.styleToken.navBtnColor.desc",
    type: "color",
    defaultValue: "",
    cssFallback: "inherit",
    category: "core",
  },
  {
    variable: "--nav-btn-active-color",
    label: "按钮激活颜色",
    description: "按钮按下或激活时的图标与背景高亮色",
    labelKey: "lets-nav-helper.styleToken.navBtnActiveColor.label",
    descriptionKey: "lets-nav-helper.styleToken.navBtnActiveColor.desc",
    type: "color",
    defaultValue: "",
    cssFallback: "#007aff",
    category: "core",
  },
  {
    variable: "--nav-text-color",
    label: "标签文字颜色",
    description: "按钮下方标签文字的颜色",
    labelKey: "lets-nav-helper.styleToken.navTextColor.label",
    descriptionKey: "lets-nav-helper.styleToken.navTextColor.desc",
    type: "color",
    defaultValue: "",
    cssFallback: "inherit",
    category: "core",
  },
  {
    variable: "--nav-height",
    label: "导航栏高度",
    description: "移动端导航栏垂直高度",
    labelKey: "lets-nav-helper.styleToken.navHeight.label",
    descriptionKey: "lets-nav-helper.styleToken.navHeight.desc",
    type: "size",
    defaultValue: "52px",
    cssFallback: "52px",
    category: "core",
    min: 32,
    max: 80,
    step: 2,
  },
  {
    variable: "--nav-radius",
    label: "导航栏圆角",
    description: "导航栏整体圆角大小",
    labelKey: "lets-nav-helper.styleToken.navRadius.label",
    descriptionKey: "lets-nav-helper.styleToken.navRadius.desc",
    type: "size",
    defaultValue: "20px",
    cssFallback: "20px",
    category: "core",
    min: 0,
    max: 40,
    step: 2,
  },
  {
    variable: "--nav-gap",
    label: "按钮间距",
    description: "导航栏按钮之间的间距",
    labelKey: "lets-nav-helper.styleToken.navGap.label",
    descriptionKey: "lets-nav-helper.styleToken.navGap.desc",
    type: "size",
    defaultValue: "2px",
    cssFallback: "2px",
    category: "advanced",
    min: 0,
    max: 16,
    step: 1,
  },
  {
    variable: "--nav-padding",
    label: "导航栏内边距",
    description: "导航栏内部边距",
    labelKey: "lets-nav-helper.styleToken.navPadding.label",
    descriptionKey: "lets-nav-helper.styleToken.navPadding.desc",
    type: "size",
    defaultValue: "4px",
    cssFallback: "4px",
    category: "advanced",
    min: 0,
    max: 20,
    step: 1,
  },
  {
    variable: "--nav-font-size",
    label: "标签字体大小",
    description: "按钮下方标签文字大小",
    labelKey: "lets-nav-helper.styleToken.navFontSize.label",
    descriptionKey: "lets-nav-helper.styleToken.navFontSize.desc",
    type: "size",
    defaultValue: "10px",
    cssFallback: "10px",
    category: "advanced",
    min: 8,
    max: 24,
    step: 1,
  },
  {
    variable: "--nav-icon-size",
    label: "图标大小",
    description: "导航栏图标大小",
    labelKey: "lets-nav-helper.styleToken.navIconSize.label",
    descriptionKey: "lets-nav-helper.styleToken.navIconSize.desc",
    type: "size",
    defaultValue: "20px",
    cssFallback: "20px",
    category: "advanced",
    min: 12,
    max: 40,
    step: 2,
  },
  {
    variable: "--nav-opacity",
    label: "导航栏不透明度",
    description: "导航栏整体透明度 (1 = 完全不透明)",
    labelKey: "lets-nav-helper.styleToken.navOpacity.label",
    descriptionKey: "lets-nav-helper.styleToken.navOpacity.desc",
    type: "opacity",
    defaultValue: "1",
    cssFallback: "1",
    category: "advanced",
    min: 0.2,
    max: 1,
    step: 0.05,
  },
  {
    variable: "--submenu-bg",
    label: "弹窗背景色",
    description: "二级菜单弹窗的背景颜色",
    labelKey: "lets-nav-helper.styleToken.submenuBg.label",
    descriptionKey: "lets-nav-helper.styleToken.submenuBg.desc",
    type: "color",
    defaultValue: "",
    cssFallback: "var(--b3-theme-surface, white)",
    category: "submenu",
  },
  {
    variable: "--submenu-text-color",
    label: "弹窗文字颜色",
    description: "二级菜单中文字的颜色",
    labelKey: "lets-nav-helper.styleToken.submenuTextColor.label",
    descriptionKey: "lets-nav-helper.styleToken.submenuTextColor.desc",
    type: "color",
    defaultValue: "",
    cssFallback: "var(--b3-theme-on-surface, #333)",
    category: "submenu",
  },
  {
    variable: "--submenu-radius",
    label: "弹窗圆角",
    description: "二级菜单弹窗的圆角大小",
    labelKey: "lets-nav-helper.styleToken.submenuRadius.label",
    descriptionKey: "lets-nav-helper.styleToken.submenuRadius.desc",
    type: "size",
    defaultValue: "12px",
    cssFallback: "12px",
    category: "submenu",
    min: 0,
    max: 40,
    step: 2,
  },
  {
    variable: "--submenu-hover-bg",
    label: "悬停高亮色",
    description: "鼠标悬停在菜单项上时的背景色",
    labelKey: "lets-nav-helper.styleToken.submenuHoverBg.label",
    descriptionKey: "lets-nav-helper.styleToken.submenuHoverBg.desc",
    type: "color",
    defaultValue: "",
    cssFallback: "var(--b3-theme-background-light, #f8f9fa)",
    category: "submenu",
  },
  {
    variable: "--submenu-shadow",
    label: "弹窗阴影",
    description: "弹窗的阴影效果，例如 0 4px 20px rgba(0,0,0,0.15)",
    labelKey: "lets-nav-helper.styleToken.submenuShadow.label",
    descriptionKey: "lets-nav-helper.styleToken.submenuShadow.desc",
    type: "shadow",
    defaultValue: "",
    cssFallback: "var(--b3-dialog-shadow, 0 4px 20px rgba(0,0,0,0.15))",
    category: "submenu",
  },
  {
    variable: "--submenu-icon-size",
    label: "网格图标大小",
    description: "网格布局下每个图标的大小",
    labelKey: "lets-nav-helper.styleToken.submenuIconSize.label",
    descriptionKey: "lets-nav-helper.styleToken.submenuIconSize.desc",
    type: "size",
    defaultValue: "18px",
    cssFallback: "18px",
    category: "submenu",
    min: 12,
    max: 40,
    step: 2,
  },
  {
    variable: "--submenu-min-width",
    label: "弹窗最小宽度",
    description: "弹窗的最小宽度（移动端 200px，桌面端 180px）",
    labelKey: "lets-nav-helper.styleToken.submenuMinWidth.label",
    descriptionKey: "lets-nav-helper.styleToken.submenuMinWidth.desc",
    type: "size",
    defaultValue: "",
    cssFallback: "180px",
    category: "submenu",
    min: 100,
    max: 400,
    step: 10,
  },
  {
    variable: "--submenu-max-width",
    label: "弹窗最大宽度",
    description: "弹窗的最大宽度（移动端 250px，桌面端 200px）",
    labelKey: "lets-nav-helper.styleToken.submenuMaxWidth.label",
    descriptionKey: "lets-nav-helper.styleToken.submenuMaxWidth.desc",
    type: "size",
    defaultValue: "",
    cssFallback: "200px",
    category: "submenu",
    min: 150,
    max: 500,
    step: 10,
  },
]
